version: '3'
services:
    api:
        ports:
            - '4000:4000'
    
    web:
        build:
            args:
                - API_URL=http://localhost:4000/v1/
        ports:
            - '80:80'