version: '3'
services:
    api:
        build:
            context: ./photos-api
            dockerfile: Dockerfile
        ports:
            - '4000:4000'
    
    web:
        build:
            context: ./photos-web
            dockerfile: Dockerfile
            args:
                - API_URL=http://localhost:4000/v1/
        ports:
            - '80:80'